package org.user;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class LoginServlet
 */
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		    response.setContentType("text/html");  
		    PrintWriter out = response.getWriter();  
		          
		    String n=request.getParameter("userName");  
		    String p=request.getParameter("userPass");  
		          
		    if(p.equals("servlet")){  
		    	
		        RequestDispatcher rd=request.getRequestDispatcher("/welcome");  
		     // forwarding to another servlet
		        rd.forward(request, response);  
		    }else if (p.equals("admin")) {
		    	// forwarding to another servlet
		    	 RequestDispatcher rd=request.getRequestDispatcher("/admin");  
			        rd.forward(request, response);  
		    }
		    else{  
		        out.print("Sorry UserName or Password Error! "+n);  
		        out.print("<br/> Included login servlet content");
		        RequestDispatcher rd=request.getRequestDispatcher("/index.html");  
		     // including response generated by this servlet and sent back to client  
		        rd.include(request, response);  
		                      
		        }  
	}
	
	public void doGet(HttpServletRequest request, HttpServletResponse response){  
        try{  
  
        response.setContentType("text/html");  
        PrintWriter out = response.getWriter();  
          
        String userName=request.getParameter("userName");  
        String address=request.getParameter("address");  
        String age=request.getParameter("age"); 
        out.print("Welcome to login screen "+userName); 
        out.print("Welcome to login screen "+address);  
        out.print("Welcome to login screen "+age); 
        
        out.close();  
  
                }catch(Exception e){System.out.println(e);}  
    } 

}
