package org.user;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Enumeration;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class LoginServlet
 */
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		    response.setContentType("text/html");  
		    PrintWriter out = response.getWriter();  
		          
		    String n=request.getParameter("userName");  
		    String p=request.getParameter("userPass");  
		          
		    if(p.equals("servlet")){  
		    	
		        RequestDispatcher rd=request.getRequestDispatcher("/welcome");  
		     // forwarding to another servlet
		        rd.forward(request, response);  
		    }else if (p.equals("admin")) {
		    	// forwarding to another servlet
		    	 RequestDispatcher rd=request.getRequestDispatcher("/admin");  
			        rd.forward(request, response);  
		    }
		    else{  
		        out.print("Sorry UserName or Password Error! "+n);  
		        out.print("<br/> Included login servlet content");
		        out.println("<table>\r\n"
		        		+ "        <!-- Table Header Section -->\r\n"
		        		+ "        <thead>\r\n"
		        		+ "            <tr>\r\n"
		        		+ "                <th>"+n+"</th>\r\n"
		        		+ "                <th>"+p+"</th>\r\n"
		        		+ "                <th>Price</th>\r\n"
		        		+ "            </tr>\r\n"
		        		+ "        </thead>\r\n"
		        		+ "        \r\n"
		        		+ "        <!-- Table Body Section -->\r\n"
		        		+ "        <tbody>\r\n"
		        		+ "            <tr>\r\n"
		        		+ "                <td>Laptop</td>\r\n"
		        		+ "                <td>10</td>\r\n"
		        		+ "                <td>$800</td>\r\n"
		        		+ "            </tr>\r\n"
		        		+ "            <tr>\r\n"
		        		+ "                <td>Keyboard</td>\r\n"
		        		+ "                <td>25</td>\r\n"
		        		+ "                <td>$50</td>\r\n"
		        		+ "            </tr>\r\n"
		        		+ "            <tr>\r\n"
		        		+ "                <td>Mouse</td>\r\n"
		        		+ "                <td>30</td>\r\n"
		        		+ "                <td>$25</td>\r\n"
		        		+ "            </tr>\r\n"
		        		+ "        </tbody>\r\n"
		        		+ "    </table>");
		        RequestDispatcher rd=request.getRequestDispatcher("/index.html");  
		     // including response generated by this servlet and sent back to client  
		        rd.include(request, response);  
		                      
		        }  
	}
	
	public void doGet(HttpServletRequest request, HttpServletResponse response){  
        try{  
  
        response.setContentType("text/html");  
        PrintWriter out = response.getWriter();  
          
        String userName=request.getParameter("userName");  
        String address=request.getParameter("address");  
        String age=request.getParameter("age"); 
        out.print("Welcome to login screen "+userName); 
        out.print("Welcome to login screen "+address);  
        out.print("Welcome to login screen "+age); 
        
        out.print("<br><br>"); 
	    out.print("======================================="); 
	    // Servlet Context Scope --Global
	    
	    ServletContext context=getServletContext();  
	    Enumeration<String> contextEnum=context.getInitParameterNames();  
	          
	    String conetxtparam="";  
	    while(contextEnum.hasMoreElements()){  
	    	conetxtparam=contextEnum.nextElement();  
	    	out.print("<br>Name: "+conetxtparam);  
	        out.print("<br>value: "+context.getInitParameter(conetxtparam));  
	    }  
	    
	    out.close();  
	      
  
                }catch(Exception e){System.out.println(e);}  
    } 

}
